{{- if and (include "cmp-issuer.managerEnabled" .) .Values.certManagerApproval.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cmp-issuer.resourceName" (dict "suffix" "cert-manager-approver" "context" $) }}
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - cmpissuers.certmanager.misiektoja.github.io/*
  {{- if not .Values.rbac.namespaced }}
  - cmpclusterissuers.certmanager.misiektoja.github.io/*
  {{- end }}
{{- end }}
