apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cmp-issuer.resourceName" (dict "suffix" "credential-reader-rolebinding" "context" $) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cmp-issuer.resourceName" (dict "suffix" "credential-reader" "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "cmp-issuer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
