---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
- apiGroups:
  - certmanager.misiektoja.github.io
  resources:
  - cmpclusterissuers
  - cmpissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.misiektoja.github.io
  resources:
  - cmpclusterissuers/status
  - cmpissuers/status
  - cmptransactions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certmanager.misiektoja.github.io
  resources:
  - cmptransactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
