//go:build !ignore_autogenerated

/*
Copyright 2026 The cmp-issuer Authors.

SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPClusterIssuer) DeepCopyInto(out *CMPClusterIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPClusterIssuer.
func (in *CMPClusterIssuer) DeepCopy() *CMPClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(CMPClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CMPClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPClusterIssuerList) DeepCopyInto(out *CMPClusterIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CMPClusterIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPClusterIssuerList.
func (in *CMPClusterIssuerList) DeepCopy() *CMPClusterIssuerList {
	if in == nil {
		return nil
	}
	out := new(CMPClusterIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CMPClusterIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPIssuer) DeepCopyInto(out *CMPIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPIssuer.
func (in *CMPIssuer) DeepCopy() *CMPIssuer {
	if in == nil {
		return nil
	}
	out := new(CMPIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CMPIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPIssuerList) DeepCopyInto(out *CMPIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CMPIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPIssuerList.
func (in *CMPIssuerList) DeepCopy() *CMPIssuerList {
	if in == nil {
		return nil
	}
	out := new(CMPIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CMPIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPIssuerSpec) DeepCopyInto(out *CMPIssuerSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Protocol.DeepCopyInto(&out.Protocol)
	in.Protection.DeepCopyInto(&out.Protection)
	out.CMPTrust = in.CMPTrust
	in.Transport.DeepCopyInto(&out.Transport)
	out.Transaction = in.Transaction
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPIssuerSpec.
func (in *CMPIssuerSpec) DeepCopy() *CMPIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(CMPIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPIssuerStatus) DeepCopyInto(out *CMPIssuerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPIssuerStatus.
func (in *CMPIssuerStatus) DeepCopy() *CMPIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(CMPIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPTransaction) DeepCopyInto(out *CMPTransaction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPTransaction.
func (in *CMPTransaction) DeepCopy() *CMPTransaction {
	if in == nil {
		return nil
	}
	out := new(CMPTransaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CMPTransaction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPTransactionList) DeepCopyInto(out *CMPTransactionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CMPTransaction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPTransactionList.
func (in *CMPTransactionList) DeepCopy() *CMPTransactionList {
	if in == nil {
		return nil
	}
	out := new(CMPTransactionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CMPTransactionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPTransactionSpec) DeepCopyInto(out *CMPTransactionSpec) {
	*out = *in
	if in.TransactionID != nil {
		in, out := &in.TransactionID, &out.TransactionID
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	in.Deadline.DeepCopyInto(&out.Deadline)
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(TransactionIssuerReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPTransactionSpec.
func (in *CMPTransactionSpec) DeepCopy() *CMPTransactionSpec {
	if in == nil {
		return nil
	}
	out := new(CMPTransactionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPTransactionStatus) DeepCopyInto(out *CMPTransactionStatus) {
	*out = *in
	if in.IssuedChain != nil {
		in, out := &in.IssuedChain, &out.IssuedChain
		*out = make([][]byte, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]byte, len(*in))
				copy(*out, *in)
			}
		}
	}
	in.CompletionTime.DeepCopyInto(&out.CompletionTime)
	if in.RecipNonce != nil {
		in, out := &in.RecipNonce, &out.RecipNonce
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.RequestNonce != nil {
		in, out := &in.RequestNonce, &out.RequestNonce
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CertReqID != nil {
		in, out := &in.CertReqID, &out.CertReqID
		*out = new(int64)
		**out = **in
	}
	if in.ResponseSigner != nil {
		in, out := &in.ResponseSigner, &out.ResponseSigner
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPTransactionStatus.
func (in *CMPTransactionStatus) DeepCopy() *CMPTransactionStatus {
	if in == nil {
		return nil
	}
	out := new(CMPTransactionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMPTrustSpec) DeepCopyInto(out *CMPTrustSpec) {
	*out = *in
	out.CASecretRef = in.CASecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMPTrustSpec.
func (in *CMPTrustSpec) DeepCopy() *CMPTrustSpec {
	if in == nil {
		return nil
	}
	out := new(CMPTrustSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordBasedMacAlgorithmSpec) DeepCopyInto(out *PasswordBasedMacAlgorithmSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordBasedMacAlgorithmSpec.
func (in *PasswordBasedMacAlgorithmSpec) DeepCopy() *PasswordBasedMacAlgorithmSpec {
	if in == nil {
		return nil
	}
	out := new(PasswordBasedMacAlgorithmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordBasedMacSpec) DeepCopyInto(out *PasswordBasedMacSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.Algorithm = in.Algorithm
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordBasedMacSpec.
func (in *PasswordBasedMacSpec) DeepCopy() *PasswordBasedMacSpec {
	if in == nil {
		return nil
	}
	out := new(PasswordBasedMacSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectionSpec) DeepCopyInto(out *ProtectionSpec) {
	*out = *in
	if in.PasswordBasedMac != nil {
		in, out := &in.PasswordBasedMac, &out.PasswordBasedMac
		*out = new(PasswordBasedMacSpec)
		**out = **in
	}
	if in.Signature != nil {
		in, out := &in.Signature, &out.Signature
		*out = new(SignatureProtectionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectionSpec.
func (in *ProtectionSpec) DeepCopy() *ProtectionSpec {
	if in == nil {
		return nil
	}
	out := new(ProtectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolSpec) DeepCopyInto(out *ProtocolSpec) {
	*out = *in
	if in.P10CRResponseCertReqID != nil {
		in, out := &in.P10CRResponseCertReqID, &out.P10CRResponseCertReqID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolSpec.
func (in *ProtocolSpec) DeepCopy() *ProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(ProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureProtectionSpec) DeepCopyInto(out *SignatureProtectionSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureProtectionSpec.
func (in *SignatureProtectionSpec) DeepCopy() *SignatureProtectionSpec {
	if in == nil {
		return nil
	}
	out := new(SignatureProtectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSTransportSpec) DeepCopyInto(out *TLSTransportSpec) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.ClientCertificateSecretRef != nil {
		in, out := &in.ClientCertificateSecretRef, &out.ClientCertificateSecretRef
		*out = new(LocalSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSTransportSpec.
func (in *TLSTransportSpec) DeepCopy() *TLSTransportSpec {
	if in == nil {
		return nil
	}
	out := new(TLSTransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransactionIssuerReference) DeepCopyInto(out *TransactionIssuerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransactionIssuerReference.
func (in *TransactionIssuerReference) DeepCopy() *TransactionIssuerReference {
	if in == nil {
		return nil
	}
	out := new(TransactionIssuerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransactionSpec) DeepCopyInto(out *TransactionSpec) {
	*out = *in
	out.MaximumDuration = in.MaximumDuration
	out.MinimumPollInterval = in.MinimumPollInterval
	out.MaximumPollInterval = in.MaximumPollInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransactionSpec.
func (in *TransactionSpec) DeepCopy() *TransactionSpec {
	if in == nil {
		return nil
	}
	out := new(TransactionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportSpec) DeepCopyInto(out *TransportSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSTransportSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportSpec.
func (in *TransportSpec) DeepCopy() *TransportSpec {
	if in == nil {
		return nil
	}
	out := new(TransportSpec)
	in.DeepCopyInto(out)
	return out
}
