apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
{{- if .Values.rbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  name: {{ include "cmp-issuer.resourceName" (dict "suffix" "credential-reader" "context" $) }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
